apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mahirahmed691/k8s-manifests.git  # Correct URL
    targetRevision: HEAD  # Track the latest commit
    path: apps/gitops  # Path to the folder containing the deployment.yaml
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server
    namespace: gitops  # Namespace for deployment (change to 'default' if required)
  syncPolicy:
    automated:
      prune: true  # Automatically prune resources not defined in the repo
      selfHeal: true  # Automatically sync if there is a drift from the desired state
